id: AEF8080DF
title: Prayer to Lord Marpa, Consort and Heirs
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:44:04.919266
  last_modified_at: 2022-03-01 00:44:04.919269
