id: AEF8080DF
title: 'Song of Devotion: A Prayer to Lord Marpa Lotsāwa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:44:04.921268
  last_modified_at: 2022-03-01 00:44:04.921270
