id: AEF8080DF
title: Guru Yoga of Lord Marpa LotsÄwa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:44:04.917901
  last_modified_at: 2022-03-01 00:44:04.917904
