id: AEF8080DF
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:44:04.927349
  last_modified_at: 2022-03-01 00:44:04.927354
