id: AEF8080DF
title: 'A Drop of Sunshine: A Guru Yoga for Lord Marpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:44:04.916538
  last_modified_at: 2022-03-01 00:44:04.916543
